<div data-layer="|" style="width: 16.43px; height: 41px; left: 2005px; top: 31px; position: absolute; justify-content: center; display: flex; flex-direction: column; color: #464646; font-size: 30px; font-family: Open Sans; font-weight: 300; line-height: 42px; word-wrap: break-word">|</div>
  <div data-layer="Line 4" class="Line4" style="width: 1746px; height: 0px; left: 306px; top: 181.50px; position: absolute; outline: 1px black solid; outline-offset: -0.50px"></div>
  <div data-layer="Line 5" class="Line5" style="width: 1746px; height: 0px; left: 306px; top: 280px; position: absolute; outline: 1px black solid; outline-offset: -0.50px"></div>
  <div data-layer="Air curve design" class="AirCurveDesign" style="left: 330px; top: 221px; position: absolute; color: #00473E; font-size: 14px; font-family: Open Sans; font-weight: 600; text-transform: uppercase; line-height: 20px; word-wrap: break-word">Air curve design</div>
  <div data-layer="Turbosilent BLDC" class="TurbosilentBldc" style="left: 543px; top: 221px; position: absolute; color: black; font-size: 14px; font-family: Open Sans; font-weight: 600; text-transform: uppercase; line-height: 20px; word-wrap: break-word">Turbosilent BLDC</div>
  <div data-layer="M.a.s.s" class="MASS" style="left: 764px; top: 221px; position: absolute; color: black; font-size: 14px; font-family: Open Sans; font-weight: 600; text-transform: uppercase; line-height: 20px; word-wrap: break-word">M.a.s.s</div>
  <div data-layer="S.c.a.n" class="SCAN" style="left: 1128px; top: 221px; position: absolute; color: black; font-size: 14px; font-family: Open Sans; font-weight: 600; text-transform: uppercase; line-height: 20px; word-wrap: break-word">S.c.a.n</div>
  <div data-layer="Lumiambience" class="Lumiambience" style="left: 918px; top: 221px; position: absolute; color: black; font-size: 14px; font-family: Open Sans; font-weight: 600; text-transform: uppercase; line-height: 20px; word-wrap: break-word">Lumiambience</div>
  <div data-layer="Line 6" class="Line6" style="width: 41px; height: 0px; left: 500px; top: 210px; position: absolute; transform: rotate(90deg); transform-origin: top left; outline: 1px black solid; outline-offset: -0.50px"></div>
  <div data-layer="Line 7" class="Line7" style="width: 41px; height: 0px; left: 721px; top: 210px; position: absolute; transform: rotate(90deg); transform-origin: top left; outline: 1px black solid; outline-offset: -0.50px"></div>
  <div data-layer="Line 8" class="Line8" style="width: 41px; height: 0px; left: 867px; top: 210px; position: absolute; transform: rotate(90deg); transform-origin: top left; outline: 1px black solid; outline-offset: -0.50px"></div>
  <div data-layer="Line 9" class="Line9" style="width: 41px; height: 0px; left: 1068px; top: 210px; position: absolute; transform: rotate(90deg); transform-origin: top left; outline: 1px black solid; outline-offset: -0.50px"></div>
  <div data-layer="Strong → A true" class="StrongATrue" style="width: 894px; height: 182px; left: 1219px; top: 379px; position: absolute"><span style="color: #00473E; font-size: 80px; font-family: Barlow Condensed; font-weight: 500; line-height: 100px; word-wrap: break-word">Introducing Air Curve Design: </span><span style="color: #00473E; font-size: 80px; font-family: Barlow Condensed; font-weight: 300; line-height: 100px; word-wrap: break-word">Redefining Ceiling Fan Efficiency<br/></span></div>
  <div data-layer="Strong → A true" class="StrongATrue" style="width: 807px; height: 99px; left: 306px; top: 979px; position: absolute; justify-content: center; display: flex; flex-direction: column; color: #00473E; font-size: 80px; font-family: Barlow Condensed; font-weight: 400; line-height: 100px; word-wrap: break-word">What is Air Curve Design?</div>
  <div data-layer="Strong → A true" class="StrongATrue" style="width: 906px; height: 99px; left: 306px; top: 1572px; position: absolute; justify-content: center; display: flex; flex-direction: column; color: #00473E; font-size: 80px; font-family: Barlow Condensed; font-weight: 400; line-height: 100px; word-wrap: break-word">Key Features of Air Curve Design</div>
  <div data-layer="Strong → A true" class="StrongATrue" style="width: 1004px; height: 99px; left: 1212px; top: 2382px; position: absolute; justify-content: center; display: flex; flex-direction: column; color: #00473E; font-size: 80px; font-family: Barlow Condensed; font-weight: 400; line-height: 100px; word-wrap: break-word">The Science Behind Air Curve Design</div>
  <div data-layer="Strong → A true" class="StrongATrue" style="width: 391px; height: 99px; left: 498px; top: 1765px; position: absolute; justify-content: center; display: flex; flex-direction: column; color: #00473E; font-size: 54px; font-family: Barlow Condensed; font-weight: 400; line-height: 100px; word-wrap: break-word">High Air Delivery</div>
  <div data-layer="Strong → A true" class="StrongATrue" style="width: 391px; height: 99px; left: 498px; top: 2033px; position: absolute; justify-content: center; display: flex; flex-direction: column; color: #00473E; font-size: 54px; font-family: Barlow Condensed; font-weight: 400; line-height: 100px; word-wrap: break-word">Advanced Materials</div>
  <div data-layer="Strong → A true" class="StrongATrue" style="width: 391px; height: 99px; left: 1493px; top: 2033px; position: absolute; justify-content: center; display: flex; flex-direction: column; color: #00473E; font-size: 54px; font-family: Barlow Condensed; font-weight: 400; line-height: 100px; word-wrap: break-word">Silent Performance</div>
  <div data-layer="Strong → A true" class="StrongATrue" style="width: 391px; height: 99px; left: 1493px; top: 1765px; position: absolute; justify-content: center; display: flex; flex-direction: column; color: #00473E; font-size: 54px; font-family: Barlow Condensed; font-weight: 400; line-height: 100px; word-wrap: break-word">Energy Efficiency</div>